name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest  # GitHub ActionsでUbuntu環境で実行

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Set permissions for chromedriver
      run: chmod +x __tests__/chromedriver_ubuntu  # Ubuntu用chromedriverに実行権限を付与

    - name: Run Selenium tests
      run: |
        python __tests__/test_todo.py
