name: Run Selenium Tests

on:
  push:
    branches:
      - main   # 例えばmainブランチにpushされたときに実行
  pull_request:
    branches:
      - main   # プルリクエストが作成されたときにも実行

jobs:
  selenium-test:
    runs-on: ubuntu-latest  # Ubuntu環境でテストを実行

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # 必要に応じてPythonのバージョンを設定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install webdriver-manager

    - name: Set up ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        export PATH=$PATH:/usr/lib/chromium-browser/chromedriver
        export CHROME_BIN=/usr/bin/chromium-browser

    - name: Run Selenium tests
      run: |
        python __tests__/test_todo.py